steps:
  - command: cd hacks && docker build -t taskintrospection-build .
  - wait
  - command: ./.buildkite/build.sh
    plugins:
      - docker#v3.9.0:
          image: "taskintrospection-build:latest"
  #- command: 
  #  artifact_paths: "*.log;build/distributions/*.deb;build/distributions/*.tar;build/distributions/*.tar.gz;*.out"
  #- wait
  #- trigger: titus-upload-debs
  #  async: false
  ##  branches:
  #    - master
  #  build:
  #    env:
  #      CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
  #      CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
  #      CALLER_UPLOAD_DEB: "build/distributions/titus-executor_latest.deb"
  #      CALLER_PACKAGE_NAME: "titus-executor"
  #      BUILDKITE_CLEAN_CHECKOUT: "true"
