steps:
  - command: cd hacks && docker build -t taskintrospection-build:${BUILDKITE_BUILD_ID} .
  - wait
  - command: make package
    artifact_paths: "build/*.deb"
    plugins:
      - docker#v3.9.0:
          image: taskintrospection-build:${BUILDKITE_BUILD_ID}
  - wait
  - trigger: titus-upload-debs
    async: false
    branches:
      - main
    build:
      env:
        CALLER_BUILD_ID: "${BUILDKITE_BUILD_ID}"
        CALLER_JOB_ID: "${BUILDKITE_JOB_ID}"
        CALLER_UPLOAD_DEB: "build/taskintrospection_latest.deb"
        CALLER_PACKAGE_NAME: "taskintrospection"
        BUILDKITE_CLEAN_CHECKOUT: "true"
